alias: "Water Sensor: Alert"
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.bathroom_water_sensor
      - binary_sensor.guest_bathroom_water_sensor
      - binary_sensor.kitchen_water_sensor
    from: "off"
    to: "on"
condition: []
action:
  - service: notify.mobile_app_bretts_iphone
    data:
      title: Alert! There is water in the house
      message: The {{ trigger.to_state.attributes.friendly_name }} is wet.
mode: single
